import Foundation

final class CleanupService: ObservableObject {
    @Published private(set) var targets: [CleanupTarget] = []

    func buildTargets() {
        let home = FileManager.default.homeDirectoryForCurrentUser
        let caches = home.appendingPathComponent("Library/Caches")
        let logs = home.appendingPathComponent("Library/Logs")
        let derivedData = home.appendingPathComponent("Library/Developer/Xcode/DerivedData")
        let archives = home.appendingPathComponent("Library/Developer/Xcode/Archives")
        let containers = home.appendingPathComponent("Library/Containers")
        let appSupport = home.appendingPathComponent("Library/Application Support")
        let trash = home.appendingPathComponent(".Trash")
        let downloads = home.appendingPathComponent("Downloads")

        var newTargets: [CleanupTarget] = []
        
        // Safe cleanup targets
        newTargets.append(
            CleanupTarget(
                title: "App Caches",
                description: "Cached data from applications. Safe to delete - apps will regenerate this data as needed.",
                scope: .safe,
                paths: [caches],
                estimatedBytes: FileIndexer.sizeOfPath(caches),
                icon: "internaldrive"
            )
        )
        
        newTargets.append(
            CleanupTarget(
                title: "Application Logs",
                description: "Log files created by apps. Useful for debugging but often unnecessary.",
                scope: .safe,
                paths: [logs],
                estimatedBytes: FileIndexer.sizeOfPath(logs),
                icon: "doc.text"
            )
        )
        
        newTargets.append(
            CleanupTarget(
                title: "Xcode Build Data",
                description: "Derived data and archives from Xcode. Can be regenerated by rebuilding projects.",
                scope: .safe,
                paths: [derivedData, archives],
                estimatedBytes: FileIndexer.sizeOfPath(derivedData) + FileIndexer.sizeOfPath(archives),
                icon: "hammer"
            )
        )
        
        newTargets.append(
            CleanupTarget(
                title: "Trash",
                description: "Files in your Trash folder waiting to be permanently deleted.",
                scope: .safe,
                paths: [trash],
                estimatedBytes: FileIndexer.sizeOfPath(trash),
                icon: "trash"
            )
        )
        
        // Aggressive cleanup targets
        newTargets.append(
            CleanupTarget(
                title: "Downloads Folder",
                description: "Files in your Downloads folder. Review before deleting!",
                scope: .aggressive,
                paths: [downloads],
                estimatedBytes: FileIndexer.sizeOfPath(downloads),
                icon: "arrow.down.circle"
            )
        )
        
        newTargets.append(
            CleanupTarget(
                title: "App Containers",
                description: "Sandboxed app data. May reset app preferences and data.",
                scope: .aggressive,
                paths: [containers],
                estimatedBytes: FileIndexer.sizeOfPath(containers),
                icon: "shippingbox"
            )
        )
        
        newTargets.append(
            CleanupTarget(
                title: "Application Support",
                description: "App settings and data. May remove important app configurations.",
                scope: .aggressive,
                paths: [appSupport],
                estimatedBytes: FileIndexer.sizeOfPath(appSupport),
                icon: "folder.badge.gearshape"
            )
        )

        // Filter out zero-size targets and sort by size
        targets = newTargets
            .filter { $0.estimatedBytes > 0 }
            .sorted { $0.estimatedBytes > $1.estimatedBytes }
    }
}
